// src/lib/mock-data.ts
import type { Agent, Task, Activity } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Sarah Chen",
    role: "Product Lead",
    badge: "Lead",
    avatar: "https://i.pravatar.cc/150?u=sarah",
    status: "active",
    currentTaskId: "task-2",
    sessionKey: "agent:main:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T08:30:00Z",
  },
  {
    id: "agent-2",
    name: "Marcus Rodriguez",
    role: "Senior Engineer",
    badge: null,
    avatar: "https://i.pravatar.cc/150?u=marcus",
    status: "active",
    currentTaskId: null,
    sessionKey: "agent:product-analyst:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T07:00:00Z",
  },
  {
    id: "agent-3",
    name: "Emily Watson",
    role: "Designer",
    badge: null,
    avatar: "https://i.pravatar.cc/150?u=emily",
    status: "idle",
    currentTaskId: "task-3",
    sessionKey: "agent:developer:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T09:15:00Z",
  },
  {
    id: "agent-4",
    name: "David Kim",
    role: "Backend Developer",
    badge: null,
    avatar: "https://i.pravatar.cc/150?u=david",
    status: "blocked",
    currentTaskId: null,
    sessionKey: "agent:backend:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T06:00:00Z",
  },
  {
    id: "agent-5",
    name: "Lisa Thompson",
    role: "QA Engineer",
    badge: null,
    avatar: "https://i.pravatar.cc/150?u=lisa",
    status: "active",
    currentTaskId: null,
    sessionKey: "agent:qa:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T05:00:00Z",
  },
  {
    id: "agent-6",
    name: "Alex Morgan",
    role: "DevOps",
    badge: null,
    avatar: "https://i.pravatar.cc/150?u=alex",
    status: "idle",
    currentTaskId: null,
    sessionKey: "agent:devops:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T04:00:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Design system audit",
    description: "Review and document all existing design tokens and component patterns",
    status: "backlog",
    createdAt: "2025-02-03T10:00:00Z",
    updatedAt: "2025-02-03T10:00:00Z",
    assignees: [mockAgents[2]],
  },
  {
    id: "task-2",
    title: "API rate limiting",
    description: "Implement rate limiting for public API endpoints",
    status: "backlog",
    createdAt: "2025-02-04T10:00:00Z",
    updatedAt: "2025-02-04T10:00:00Z",
    assignees: [mockAgents[3]],
  },
  {
    id: "task-3",
    title: "User dashboard redesign",
    description: "Create new wireframes and mockups for the main dashboard",
    status: "in_progress",
    createdAt: "2025-02-02T14:00:00Z",
    updatedAt: "2025-02-04T08:30:00Z",
    assignees: [mockAgents[0]],
  },
  {
    id: "task-4",
    title: "Database optimization",
    description: "Optimize slow queries identified in performance monitoring",
    status: "in_progress",
    createdAt: "2025-02-01T09:00:00Z",
    updatedAt: "2025-02-04T07:00:00Z",
    assignees: [mockAgents[1]],
  },
  {
    id: "task-5",
    title: "Authentication flow",
    description: "Implement OAuth2 social login options",
    status: "review",
    createdAt: "2025-01-30T11:00:00Z",
    updatedAt: "2025-02-03T16:00:00Z",
    assignees: [mockAgents[3]],
  },
  {
    id: "task-6",
    title: "Mobile responsive fixes",
    description: "Fix layout issues on mobile viewports for settings page",
    status: "review",
    createdAt: "2025-01-29T07:00:00Z",
    updatedAt: "2025-02-02T12:00:00Z",
    assignees: [mockAgents[2]],
  },
  {
    id: "task-7",
    title: "CI/CD pipeline setup",
    description: "Configure automated testing and deployment workflows",
    status: "done",
    createdAt: "2025-01-28T10:00:00Z",
    updatedAt: "2025-01-30T15:00:00Z",
    assignees: [mockAgents[5]],
  },
  {
    id: "task-8",
    title: "User onboarding flow",
    description: "Design and implement new user welcome experience",
    status: "done",
    createdAt: "2025-01-25T09:00:00Z",
    updatedAt: "2025-01-28T14:00:00Z",
    assignees: [mockAgents[0]],
  },
  {
    id: "task-9",
    title: "Error tracking integration",
    description: "Set up Sentry for error monitoring and alerting",
    status: "done",
    createdAt: "2025-01-24T08:00:00Z",
    updatedAt: "2025-01-26T11:00:00Z",
    assignees: [mockAgents[4]],
  },
];

export const mockActivities: Activity[] = [
  {
    id: "activity-1",
    type: "moved",
    agentId: "agent-1",
    taskId: "task-3",
    message: "Backlog → In Progress",
    createdAt: "2025-02-04T09:15:00Z",
    agent: mockAgents[0],
    task: mockTasks[2],
  },
  {
    id: "activity-2",
    type: "commented",
    agentId: "agent-2",
    taskId: "task-4",
    message: "Added performance metrics",
    createdAt: "2025-02-04T08:30:00Z",
    agent: mockAgents[1],
    task: mockTasks[3],
  },
  {
    id: "activity-3",
    type: "created",
    agentId: "agent-3",
    taskId: "task-1",
    message: "Design system audit",
    createdAt: "2025-02-04T07:00:00Z",
    agent: mockAgents[2],
    task: mockTasks[0],
  },
  {
    id: "activity-4",
    type: "moved",
    agentId: "agent-4",
    taskId: "task-5",
    message: "In Progress → Review",
    createdAt: "2025-02-04T06:30:00Z",
    agent: mockAgents[3],
    task: mockTasks[4],
  },
  {
    id: "activity-5",
    type: "commented",
    agentId: "agent-5",
    taskId: "task-9",
    message: "All tests passing",
    createdAt: "2025-02-04T05:00:00Z",
    agent: mockAgents[4],
    task: mockTasks[8],
  },
  {
    id: "activity-6",
    type: "moved",
    agentId: "agent-6",
    taskId: "task-7",
    message: "Review → Done",
    createdAt: "2025-02-04T04:00:00Z",
    agent: mockAgents[5],
    task: mockTasks[6],
  },
  {
    id: "activity-7",
    type: "created",
    agentId: "agent-1",
    taskId: "task-2",
    message: "API rate limiting",
    createdAt: "2025-02-04T03:00:00Z",
    agent: mockAgents[0],
    task: mockTasks[1],
  },
  {
    id: "activity-8",
    type: "moved",
    agentId: "agent-2",
    taskId: "task-6",
    message: "In Progress → Review",
    createdAt: "2025-02-04T02:00:00Z",
    agent: mockAgents[1],
    task: mockTasks[5],
  },
];
