// src/lib/mock-data.ts
import type { Agent, Task, Activity } from "./types";

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Jarvis",
    role: "Squad Lead",
    badge: "Lead",
    avatar: "🤖",
    status: "active",
    currentTaskId: "task-2",
    sessionKey: "agent:main:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T08:30:00Z",
  },
  {
    id: "agent-2",
    name: "Shuri",
    role: "Product Analyst",
    badge: null,
    avatar: "🦊",
    status: "idle",
    currentTaskId: null,
    sessionKey: "agent:product-analyst:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T07:00:00Z",
  },
  {
    id: "agent-3",
    name: "Friday",
    role: "Developer",
    badge: null,
    avatar: "⚡",
    status: "blocked",
    currentTaskId: "task-3",
    sessionKey: "agent:developer:main",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-02-04T09:15:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Research competitor pricing models",
    description: "Analyze pricing strategies of top 5 competitors in the AI agent space.",
    status: "inbox",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-02-01T10:00:00Z",
    assignees: [],
  },
  {
    id: "task-2",
    title: "Build Mission Control dashboard",
    description: "Create the main dashboard UI with kanban board, activity feed, and agent status.",
    status: "in_progress",
    createdAt: "2025-02-02T14:00:00Z",
    updatedAt: "2025-02-04T08:30:00Z",
    assignees: [mockAgents[0]],
  },
  {
    id: "task-3",
    title: "Fix WebSocket reconnection bug",
    description: "Gateway loses connection after 30 minutes. Need to implement reconnect logic.",
    status: "review",
    createdAt: "2025-02-03T09:00:00Z",
    updatedAt: "2025-02-04T09:15:00Z",
    assignees: [mockAgents[2]],
  },
  {
    id: "task-4",
    title: "Write onboarding documentation",
    description: "Create getting started guide for new users.",
    status: "done",
    createdAt: "2025-01-28T11:00:00Z",
    updatedAt: "2025-02-01T16:00:00Z",
    assignees: [mockAgents[1]],
  },
  {
    id: "task-5",
    title: "Design email templates",
    description: "Create HTML email templates for notifications.",
    status: "assigned",
    createdAt: "2025-02-04T07:00:00Z",
    updatedAt: "2025-02-04T07:00:00Z",
    assignees: [mockAgents[1]],
  },
];

export const mockActivities: Activity[] = [
  {
    id: "activity-1",
    type: "status_changed",
    agentId: "agent-3",
    taskId: "task-3",
    message: "moved to review",
    createdAt: "2025-02-04T09:15:00Z",
    agent: mockAgents[2],
    task: mockTasks[2],
  },
  {
    id: "activity-2",
    type: "message_sent",
    agentId: "agent-1",
    taskId: "task-2",
    message: "commented on",
    createdAt: "2025-02-04T08:30:00Z",
    agent: mockAgents[0],
    task: mockTasks[1],
  },
  {
    id: "activity-3",
    type: "task_created",
    agentId: "agent-2",
    taskId: "task-5",
    message: "created",
    createdAt: "2025-02-04T07:00:00Z",
    agent: mockAgents[1],
    task: mockTasks[4],
  },
  {
    id: "activity-4",
    type: "status_changed",
    agentId: "agent-1",
    taskId: "task-4",
    message: "completed",
    createdAt: "2025-02-01T16:00:00Z",
    agent: mockAgents[0],
    task: mockTasks[3],
  },
];
